
package com.xt.server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://impl.service.xt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://impl.service.xt.com/", className = "com.xt.server.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://impl.service.xt.com/", className = "com.xt.server.GetWeatherResponse")
    @Action(input = "http://impl.service.xt.com/HelloServiceImpl/getWeatherRequest", output = "http://impl.service.xt.com/HelloServiceImpl/getWeatherResponse")
    public String getWeather();

}
